# -*- coding: utf-8 -*-
import json,html
from pathlib import Path
P=Path(__file__).parent;d=json.loads((P/'all6_optimization.json').read_text())
labels={'baseline':'持有到期，不轮空','hold_gate':'持有到期＋费用轮空','symmetric':'涨跌相同固定止盈','asymmetric':'涨跌不同固定止盈','timed':'固定止盈＋指定日强制退出','trailing':'收益回撤止盈','stock_move':'股价幅度＋组合盈利退出','decay_symmetric':'涨跌相同＋时间递减','decay_asymmetric':'涨跌不同＋时间递减','decay_no_gate':'时间递减，不轮空','all_best':'全搜索最高'}
def n(x):return '—' if x is None else f'{x:,.2f}'
def m(x):return '$'+n(x)
def e(x):return html.escape(str(x))
def table(head,rows):return '<div class="scroll"><table><thead><tr>'+''.join('<th>'+x+'</th>' for x in head)+'</tr></thead><tbody>'+''.join('<tr>'+''.join('<td>'+str(x)+'</td>' for x in row)+'</tr>' for row in rows)+'</tbody></table></div>'
ranked=sorted([k for k in labels if k!='all_best'],key=lambda k:d['comparison'][k]['pnl'],reverse=True)
comparison=table(['策略类别（各自最佳参数）','六轮总毛收益','六轮总净收益','相对持有到期','参与/盈利轮数','累计买入成本','最差一轮净收益'],[[labels[k],m(sum(r['gross'] for r in d['selected_results'][k][:6])),m(d['comparison'][k]['pnl']),m(d['comparison'][k]['pnl']-d['comparison']['baseline']['pnl']),str(d['comparison'][k]['trades'])+' / '+str(d['comparison'][k]['wins']),m(d['comparison'][k]['cost']),m(d['comparison'][k]['worst'])] for k in ranked])
params=table(['策略类别','选出的具体参数'],[[labels[k],e(d['selected'][k]['name'])] for k in ranked])
profile=table(['降目标方案','一起重选初始参数后的最高净收益','初始涨/跌侧目标','轮空与止损'],[[e(x['schedule']['name']),m(x['stats']['pnl']),str(x['rule']['up'])+'% / '+str(x['rule']['down'])+'%',e(x['rule']['name'].split('；',1)[-1])] for x in d['profiles']])
ablation=table(['其他条件完全不变，仅改变时间目标','六轮总净收益','相对原固定目标'],[['固定涨侧100% / 跌侧2%',m(d['comparison']['asymmetric']['pnl']),'—']]+[[e(x['rule']['schedule']['name']),m(x['stats']['pnl']),m(x['stats']['pnl']-d['comparison']['asymmetric']['pnl'])] for x in d['ablation']])
rule=d['selected']['decay_asymmetric'];sched=rule['schedule'];stages=[('入场周五～下周二',None),('下周三',sched['wed']),('下周四',sched['thu']),('到期周五',sched['fri'])]
def target(base,a):return base if a is None else base*a['factor'] if 'factor' in a else a['absolute']
schedule_table=table(['时段（美东）','股票相对入场价≥0：净收益目标','股票相对入场价<0：净收益目标'],[[name,n(target(rule['up'],a))+'%',n(target(rule['down'],a))+'%'] for name,a in stages])
rounds=table(['周期','持有到期净收益','固定涨跌目标净收益','时间递减净收益','递减相对固定的增量','递减规则退出情况'],[[c['label'],m(d['selected_results']['baseline'][i]['pnl']),m(d['selected_results']['asymmetric'][i]['pnl']),m(d['selected_results']['decay_asymmetric'][i]['pnl']),m(d['selected_results']['decay_asymmetric'][i]['pnl']-d['selected_results']['asymmetric'][i]['pnl']),e(d['selected_results']['decay_asymmetric'][i]['reason'])+('（触发未成交）' if d['selected_results']['decay_asymmetric'][i].get('unfilled_signal') else '')] for i,c in enumerate(d['cycles'][:6])])
stress=table(['规则','买入/卖出摩擦','最大价格年龄','六轮总净收益'],[[labels[x['key']],str(round(x['slip']*100))+'%',str(x['age'])+'分钟',m(x['stats']['pnl'])] for x in d['stress'] if x['key']!='all_best'])
time_rows=[]
for x in d['time_value'][:6]:
 c=next(c for c in d['cycles'] if c['id']==x['id']);expiry=c['expiry']
 for r in x['rows']:
  from datetime import datetime
  dow=datetime.fromisoformat(r['et']).weekday()
  if dow not in [2,3]:continue
  time_rows.append([x['id'][5:],r['et'][:16].replace('T',' '),m(r['value']),m(r['intrinsic']),m(r['extrinsic']),str(r['call_age'])+' / '+str(r['put_age'])])
time_table=table(['开仓周期','周三/周四采样ET','Call＋Put市场估值','内在价值合计','剩余外在价值估计','两腿价格年龄分钟'],time_rows)
options=''.join('<option value="'+k+'"'+(' selected' if k=='decay_asymmetric' else '')+'>'+label+'</option>' for k,label in labels.items())
body=f'''<header><div class="eyebrow">SKHY · 报告3更新 · 六轮全部训练</div><h1>不同退出策略的总收益<br>加入周三、周四降低盈利要求</h1><p>固定每轮1 Call＋1 Put。7/31、8/7、8/14、8/21、8/28、9/4六个已结束周期全部参与选参与排名；9/11未到期周期仅作展示。行情截至2026/9/16。</p><a href="skhy_report2_straddle.html">原报告2</a> · <a href="all6_optimization.json">完整结果</a> · <a href="all6_rule_scores.json">全部规则评分</a></header>
<section><h2>六轮最高净收益：时间递减与固定目标并列</h2><div class="cards"><div class="card">持有到期<strong>{m(d['comparison']['baseline']['pnl'])}</strong></div><div class="card">涨跌不同 · 固定目标<strong>{m(d['comparison']['asymmetric']['pnl'])}</strong></div><div class="card">涨跌不同 · 时间递减<strong>{m(d['comparison']['decay_asymmetric']['pnl'])}</strong></div></div><p>本次对 <b>{d['rules_count']:,}</b> 组规则用六轮总净收益排序，不再拆分训练和验证。网格内有 <b>{d['ties_count']}</b> 组参数并列最高。最好的时间递减规则并没有比固定目标多赚，六轮的实际退出结果相同；它只是另一组能解释当前样本的参数。</p><p class="note">如果希望明确落实“越接近到期，收益要求越低”，可把下面的时间递减方案作为这六轮选出的候选：费用比超过12%轮空；初始上涨侧150%、下跌侧2%，周三降至112.5% / 1.5%，周四降至75% / 1%，到期周五降至37.5% / 0.5%。这些均为<b>组合净收益率</b>，不是股票涨跌幅。不另设固定止损或强制提前退出。</p><p>目标降低会增加触发机会，但不会把已亏损的仓位自动变成盈利，也可能提前结束后续大幅盈利的行情。六轮都是训练数据，本报告的“最高”只表示这组数据和所列网格内的最高，不代表未来最优。</p></section>
<section><h2>不同策略的六轮总收益</h2>{comparison}<p class="muted">各类策略都在同一六轮中独立选择最佳参数，允许费用轮空的类别可能只交易部分轮次；轮空记0收益，表内同时列参与轮数和累计投入。累计买入成本是各次交易投入之和，不是账户初始资金，不年化。每轮固定一组，不复投、不在提前退出后重开本轮。</p><details><summary>展开各类最佳参数</summary>{params}</details></section>
<section><h2>时间递减方案：每天用哪个目标</h2>{schedule_table}<p>周三、周四及到期周五从09:30起切换当天目标，仍每10分钟检查一次。09:30没有已完成的当日行情时，等到符合价格年龄条件的采样点再判断。股票高于本周期实际入场价用上涨侧目标，低于则用下跌侧目标。净收益率＝（模拟卖出净收入−买入总成本）÷买入总成本。</p><p>比如周四股票在入场价上方，组合净收益达到75%就触发退出，而不再等待初始150%；若股票在入场价下方，目标为1%。这些较小收益目标已经按示例成本扣费判断，但真实价差与成交延迟仍可能把最终盈利变成亏损。</p>{rounds}<p class="muted">8/7虽触发退出，数据中没有后续两腿共同成交分钟，所以仍按到期处理。该轮利润不能全部归因于主动止盈；并列结果也可能部分受成交数据约束影响。</p></section>
<section><h2>只降低目标，和重新优化初始目标，是两件事</h2><p>先固定上一版样本内最高规则：上涨侧100%、下跌侧2%、费用上限12%、无固定止损。只加入不同的时间递减幅度，结果如下：</p>{ablation}<p>仅按周三75%、周四50%、周五25%的比例降低原目标，总净收益从$2,564.56降至$2,221.56。更激进的“周三起保本”下降更多。说明单独加速退出，并未在这六轮提高总收益。</p><p>再允许同时重选初始涨跌目标、轮空与止损，各种时间方案在本样本能达到的最好结果：</p>{profile}<p>最缓和的递减方案把初始上涨目标提高到150%，再逐日降低，才追平固定100%目标。这个结果支持比较“有时间安排的目标”，但没有证据支持越早、越大幅降低目标越好。</p></section>
<section><h2>收益曲线与实际退出时点</h2><div class="toolbar"><label>策略 <select id="strategy">{options}</select></label><label>周期 <select id="cycle"></select></label></div><p class="note" id="ruleText"></p><div id="roundTable"></div><p id="roundInfo"></p><div class="legend"><span style="color:#ffd166">金色：原持仓净估值</span><span style="color:#43caaa">绿色：所选策略净损益</span><span style="color:#38bdf8">蓝色：股票涨跌% · 右轴</span></div><div class="chartwrap"><canvas id="chart"></canvas><div id="tip"></div></div><p class="muted">绿色退出后保持已实现模拟收益；轮空为0。两条零值虚线分别对应总收益$0、股票0%。鼠标悬停查看具体数字；时间递减策略还显示当天、当前股价方向对应的退出目标。9/11的结果不计入上方总收益。</p></section>
<section><h2>时间衰竭已经体现在期权价格中，不重复扣费</h2><p>长仓期权受时间价值损耗影响，平值期权临近到期时损耗往往更快，但期权市场价同时受股价、隐含波动率等影响，不能把几天的价格下降全部当成Theta。参考 <a href="https://prd-web.optionseducation.org/advancedconcepts/theta">OIC：Theta</a>。</p><p>本回测使用真实历史期权成交价，时间价值变化已包含在收益中；因此不额外每天减一个“时间衰竭成本”，避免重复计算。此次通过降低周三、周四的退出目标应对剩余时间减少，并测试到期前保本/小亏退出。</p>{time_table}<p class="muted">外在价值估计＝100×(Call价＋Put价)−100×|股价−行权价|。每个周三、周四选两腿价格年龄≤10分钟、最接近10:00的可用观察点，实际时间列出。两腿与股票并非同秒报价，出现负外在价值表示成交价不同步或数据问题，不是负Theta，也不裁剪为0。表中差额只作观察，不等于纯时间损耗、没有作为选参信号。</p></section>
<section><h2>成本与成交条件仍会改变结果</h2>{stress}<p>标准口径：买入两腿各加2%，卖出各减2%；每张每次$0.65佣金。到期按内在价值结算，无卖出摩擦。信号只用当时已完成的当日分钟，Call和Put价格年龄≤10分钟；信号后至少一分钟，取两腿首个共同成交分钟开盘价模拟退出。若无共同分钟，则保留到期或最新估值。这不是历史Bid/Ask，不保证实际能按该价卖出。</p><p>轮空费用比在周五10:00用已完成的最新两腿价格除以参考股价计算，价格年龄≤30分钟；不是用稍后实际入场价格倒推。12%上限在当前六轮只剔除7/31，样本很少。表中总收益已扣示例成本，不代表券商实际收费。</p></section>
<section><h2>复现与口径</h2><p>六轮全部训练，不再展示旧版的三轮训练／两轮验证结论。所有策略只在开仓时做轮空判断，在盘中使用过去可知信息；未结束周期不参与选参。总收益优先，要求至少两轮成交；并列时按最差轮次、简单条件及固定编号排序。</p><p><a href="analyze_all6.py">分析程序</a> · <a href="build_all6.py">报告生成器</a> · <a href="README_all6.md">复现说明</a>。原报告1、2保留；旧版报告3已备份。这里没有额外下载新行情，以免更换样本影响策略对比。</p></section>'''
css='''*{box-sizing:border-box}body{margin:0;background:#0e121b;color:#e7edf7;font:14px/1.8 system-ui,-apple-system,"PingFang SC",sans-serif;color-scheme:dark}main{max-width:1450px;margin:auto;padding:32px 24px}h1{font-size:31px;margin:8px 0}h2{font-size:21px;margin-top:0}.eyebrow{color:#f5ca75;letter-spacing:2px}.muted,small{color:#9cabbe}section{background:#171e2c;border:1px solid #2b3546;border-radius:14px;padding:24px;margin:22px 0}a{color:#79b7ff}.cards{display:grid;grid-template-columns:repeat(3,1fr);gap:16px}.card{background:#202a3b;padding:17px;border-radius:10px}.card strong{display:block;font-size:28px;color:#f5ca75}.note{border-left:3px solid #f5ca75;background:#f5ca7509;padding:14px}.scroll{overflow:auto;max-height:520px}table{border-collapse:collapse;width:100%;font-size:13px}th,td{border-bottom:1px solid #2b3546;padding:11px;text-align:right;white-space:nowrap}th{background:#202a3b;color:#9cabbe;position:sticky;top:0}td:first-child,th:first-child{text-align:left}td:first-child{white-space:normal;min-width:115px}.toolbar,.legend{display:flex;gap:20px;flex-wrap:wrap;margin:14px 0}select{padding:9px;background:#202c3e;color:#e7edf7;border:1px solid #3b4960;border-radius:6px;font:inherit}.chartwrap{position:relative}canvas{width:100%;height:450px;display:block}#tip{position:absolute;display:none;pointer-events:none;background:#080e18f5;border:1px solid #738398;padding:12px;border-radius:9px;z-index:2;max-width:300px;font-size:12px}summary{cursor:pointer;color:#79b7ff}@media(max-width:750px){main{padding:15px}.cards{grid-template-columns:1fr}section{padding:16px}h1{font-size:24px}}'''
js=(P/'all6_chart.js').read_text()
result='<!doctype html><html lang="zh-CN"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>SKHY报告3：六轮全量训练与时间递减退出</title><style>'+css+'</style><main>'+body+'</main><script>const D='+json.dumps(d,ensure_ascii=False,allow_nan=False).replace('</','<\\/')+';\n'+js+'</script></html>'
for name in ['skhy_report3_all6_time_decay.html','skhy_report3_exit_optimization.html']:(P/name).write_text(result)
print('Generated all-six training report')
