# -*- coding: utf-8 -*-
import json,html
from pathlib import Path
P=Path(__file__).parent;d=json.loads((P/'exit_optimization.json').read_text());search=json.loads((P/'rule_search_summary.json').read_text())
def num(x):return '—' if x is None else f'{x:,.2f}'
def money(x):return '—' if x is None else f'${x:+,.2f}'
def esc(x):return html.escape(str(x))
def table(headers,rows):return '<div class="scroll"><table><thead><tr>'+''.join('<th>'+h+'</th>' for h in headers)+'</tr></thead><tbody>'+''.join('<tr>'+''.join('<td>'+str(v)+'</td>' for v in row)+'</tr>' for row in rows)+'</tbody></table></div>'
def total(key,ids):return sum(d['selected_results'][key][i]['pnl'] for i in ids)
keys={'baseline':'原策略：持有到期','train_selected':'只用前三轮选出的规则','full_sample_best':'六轮回看最高收益规则','no_gate':'训练规则，不轮空','symmetric':'训练选出的对称退出'}
summary=table(['规则','前三轮训练净收益','后两轮验证净收益','六轮总净收益','六轮交易/获利'],[[label,money(total(k,[0,1,2])),money(total(k,[4,5])),money(total(k,range(6))),str(sum(not x['skipped'] for x in d['selected_results'][k][:6]))+' / '+str(sum(x['pnl']>0 for x in d['selected_results'][k][:6]))] for k,label in keys.items()])
peaks=table(['周期','全部采样最高毛收益','两腿≤10分钟最高毛收益','同一点扣示例摩擦后','持有到期毛收益 / 最新估值'],[[x['id'][5:],money(x['gross_peak']),money(x['fresh_peak']),money(x['fresh_peak_net']),money(x['final'])] for x in d['peaks']])
feature=table(['周期','实际买入权利金/股价','10:00事前估计','近10日波动折算5日','费用/历史波动','到期下/上盈亏平衡股价涨跌'],[[f['id'][5:],num(f['premium_pct'])+'%',num(f['pretrade_pct'])+'%',num(f['rv5_pct'])+'%',num(f['expensiveness']),num(f['break_even_down_pct'])+'% / '+num(f['break_even_up_pct'])+'%'] for f in d['features']])
gates=table(['仅改变轮空，不提前退出','六轮交易数','六轮净收益','跳过周期'],[[esc(x['rule']['name']),x['stats']['trades'],money(x['stats']['pnl']),', '.join(r['id'][5:] for r in x['results'][:6] if r['skipped']) or '无'] for x in d['gates']])
wf=table(['开仓周期','当时已结束的训练周期','选出的规则','本周期净收益','状态'],[[x['cycle'][5:],', '.join(z[5:] for z in x['training']),esc(x['rule']['name']),money(x['result']['pnl']),'已退出' if x['result']['closed'] else '估值'] for x in d['walk_forward']])
stress=table(['买入加价/卖出减价','两腿信号价最大年龄','前三轮净收益','后两轮验证净收益','六轮净收益'],[[str(round(x['slip']*100))+'% / '+str(round(x['slip']*100))+'%',str(x['age_limit'])+'分钟',money(sum(x['results'][i]['pnl'] for i in [0,1,2])),money(sum(x['results'][i]['pnl'] for i in [4,5])),money(sum(r['pnl'] for r in x['results'][:6]))] for x in d['stress']])
# Same gate, no stop/cut; show neighborhood without claiming a precisely identified optimum.
neighbors=[x for x in search if x['rule']['type']=='target' and x['rule'].get('gate')==['premium',12] and x['rule'].get('stop') is None and x['rule'].get('cut') is None and x['rule']['up'] in [40,60,100,150] and x['rule']['down'] in [2,5,10,20]]
neighbor=table(['涨侧净收益阈值','跌侧净收益阈值','六轮回看净收益','后两轮（已参与该表比较）'],[[str(x['rule']['up'])+'%',str(x['rule']['down'])+'%',money(x['full']['pnl']),money(x['test']['pnl'])] for x in neighbors])
alt=json.loads((P/'execution_sensitivity.json').read_text())
execution_table=table(['同一套信号，不同成交配对','共同分钟六轮净收益','各腿分别首个后续分钟六轮净收益'],[[keys[x['strategy']],money(total(x['strategy'],range(6))),money(sum(r['pnl'] for r in x['results'][:6]))] for x in alt])
body=f'''<header><div class="eyebrow">SKHY · 报告3 · 退出与轮空策略研究</div><h1>先决定是否值得买，再区分涨跌退出</h1><p>每轮固定 1张 Call＋1张 Put；2026/7/31 起七轮，六轮已到期，一轮进行中。行情截至美东 2026/9/16。沿用报告2合约与买入时点，不修改原报告。</p><a href="skhy_report2_straddle.html">查看原报告2</a> · <a href="exit_optimization.json">下载完整计算结果</a> · <a href="rule_search_summary.json">下载全部规则评分</a></header>
<section><h2>结论：发现了候选规则，还没有验证出可靠的“最优策略”</h2><div class="cards"><div class="card">六轮原策略净收益<strong>{money(total('baseline',range(6)))}</strong></div><div class="card">六轮回看最高净收益<strong>{money(total('full_sample_best',range(6)))}</strong><small>使用全样本挑选，不能当预测</small></div><div class="card">训练规则后两轮验证<strong>{money(total('train_selected',[4,5]))}</strong><small>同期持有到期 {money(total('baseline',[4,5]))}</small></div></div>
<p>本样本更支持“上涨时允许收益继续扩大，下跌时较早落袋”的研究方向；但训练选出的规则在后续两轮落后于持有到期，不能宣布已经找到可实盘复现的最优参数。固定止损也可能在反弹前卖掉组合，例如8/28轮的50%止损把原本到期盈利变成了亏损。</p><p class="note">回看候选：10:00估计的（Call＋Put单价）÷股价超过12%时轮空；持仓后，股价相对实际入场价≥0时，组合净收益率达到100%退出；股价&lt;0时，组合净收益率达到2%退出。本次回看最高规则没有固定止损和提前时间退出。它仍包含亏损轮次，且8/7触发后没有后续共同成交分钟、实际模拟留到到期，不能把该轮利润归功于成功提前止盈。</p>
<p>更稳妥的下一步是把这套候选参数冻结后做后续周期模拟观察。12%、100%、2%均为本次网格内参数，不是已证实的市场规律；下方邻近阈值表展示结果对参数的敏感程度。跌侧2%、5%、10%在六轮中结果完全相同，不能精确识别2%为最优；训练选中2%也只是并列时的固定排序，训练交易中并未出现该阈值的成功退出。</p></section>
<section><h2>“每轮都出现正收益”需要先扣除价格与成交影响</h2>{peaks}<p>7/31最高毛收益只有$43；8/14在两腿价格年龄都不超过10分钟的观察点，最高毛收益只有$51。按买入加价2%、卖出减价2%、每张每次$0.65佣金的示例口径，两者分别为−$45.14和−$13.82。因此，小幅翻红不等于有足够的可成交净利润。</p><p class="muted">最高值只是事后观察上界，不作为规则输入；该净收益仍按观察价估算，不是“下一分钟卖出”的回测。盘中报价老化与到期收盘复核可能使全部采样最高点高于新鲜价格最高点。</p></section>
<section><h2>规则比较：训练与验证分开</h2><img src="exit_strategy_comparison.png" alt="六轮策略净收益对比" style="width:100%;border-radius:8px">{summary}<p>共比较 <b>{d['rules_count']:,}</b> 组规则：涨跌分开止盈、股价幅度止盈、收益回撤止盈、20%/35%/50%止损、周二/周三/周四15:30时间退出，以及权利金轮空条件。目标为每轮固定一组期权的累计净美元收益，训练至少成交两轮；没有按事后高点指定逐轮不同参数。</p><p>训练用7/31、8/7、8/14三轮，最后一轮到8/21收盘才结束；验证从8/28开始，使用8/28与9/4两轮。8/21周期11:41开仓早于训练结束，所以只计入全样本回看，不冒充验证。9/11未到期，完全不参与选参。所有历史已被查看，时间切分也只是回顾性验证，不是真正未见数据。</p><p><b>训练选中：</b>{esc(d['selected']['train_selected']['name'])}。<br><b>全样本回看最高：</b>{esc(d['selected']['full_sample_best']['name'])}。</p><p class="muted">表中六轮合计包含训练及重叠周期，不代表账户年化回报。各轮独立，周五上午新仓与下午到期旧仓存在资金重叠；未建立固定资金池。</p></section>
<section><h2>逐周期：退出时间、成本与结果</h2><div class="toolbar"><label>规则 <select id="strategy"><option value="train_selected">训练选中规则（默认）</option><option value="full_sample_best">全样本回看最高（事后）</option><option value="baseline">持有到期</option><option value="no_gate">训练规则：不轮空</option><option value="symmetric">对称止盈规则</option></select></label><label>周期 <select id="cycle"></select></label></div><p id="ruleText" class="note"></p><div id="roundTable"></div><p id="roundInfo"></p><div class="legend"><span style="color:#ffd166">金色：原持仓净估值</span><span style="color:#43caaa">绿色：所选规则净损益（退出后保持不变）</span><span style="color:#38bdf8">蓝色：股价涨跌% · 右轴</span></div><div class="chartwrap"><canvas id="chart"></canvas><div id="tip"></div></div><p class="muted">两条零值虚线：左轴总收益$0、右轴股票0%。鼠标查看采样时间、损益和价格年龄；曲线不跨缺价、休市或隔夜连线。已轮空的周期绿色为0；退出后的绿色为已实现模拟损益。股价始终相对报告2原始入场价，便于对照。线条是观察点连接，不把平滑曲线生成的中间值用作信号。</p></section>
<section><h2>期权贵不贵：价格占比比绝对美元金额更有用</h2>{feature}<p>事前权利金比＝10:00之前最后已完成的Call价＋Put价，再除以当时股价；两腿价格年龄须≤30分钟，否则有过滤条件的规则当轮跳过。此指标在买入前确定，不用稍后实际成交价倒推轮空。实际买入费用比仅用于复盘，尤其8/21入场延至11:41，两者不完全一致。</p><p>7/31的事前费用比为14.45%，明显高于后续轮次；12%和14%上限都只剔除了这一个已知亏损周期。它是值得观察的上限，却只有一个昂贵样本，不能据此证明12%比其他阈值最优。14.45%也不是标准差或精确IV；同一行权价的到期毛盈亏平衡点是 K ±（Call＋Put买价）。表中两端已考虑行权价偏离买入股价。</p><p>另测试“费用比÷历史波动”：用入场日前最近10个收盘对数收益的样本标准差×√5估计五日波动。该历史尺度不是未来波动预测，且没有包含财报等事件信息。9/4按这个比值偏贵，但该轮明显盈利；机械采用比值≤1会漏掉它。</p>{gates}<p class="muted">上表只改变轮空，不提前退出，用于隔离过滤的贡献；不能把过滤与退出改善混为一谈。</p></section>
<section><h2>涨跌不同退出：参数并不精确到2%</h2><p>涨跌指“当前股价相对本轮实际入场价”而不是最近10分钟方向。组合净收益率才是止盈阈值，因此“上涨侧100%”不是股票涨100%。每10分钟判断一次；亏损先检查止损，再检查止盈／回撤，最后检查时间退出。回撤是自已观察到的净收益率高点回落多少个百分点，不是股价回撤。</p>{neighbor}<p>上表固定费用上限12%、不设止损和提前时间退出，只改变涨跌两侧目标。相邻阈值可能在同一个跳空观察点一起触发，结果相同并不证明每个阈值都可靠。6轮数据无法稳定估计方向差异，更不能证明下跌必然要快卖、上涨必然要持有。</p></section>
<section><h2>逐步向前选参：只使用开仓前已经结束的周期</h2>{wf}<p>新周期周五上午开仓时，上一个周期要下午才到期，因此不能用于当周选参。每次仅以更早已结束周期重新选规则，然后应用到下一轮。这里同样是历史模拟，样本短；9/11结果虽已按退出规则平仓，原始到期对照仍未结束。</p></section>
<section><h2>成交与摩擦敏感性</h2>{stress}<p>本表保持“训练选中规则”参数固定，仅改变摩擦或信号价格年龄后重跑，包括触发时点变化。标准口径买入两腿各加2%、卖出各减2%，佣金每张每次$0.65；到期按经济内在价值结算，不扣卖出滑点及佣金。不是已取得的Bid/Ask价差。持仓未结束的值按假设平仓扣卖出摩擦估算。</p><p>信号只用当时已完成分钟；两腿最新成交分钟距观察点不超过10分钟。平仓用信号后至少一分钟的首个Call与Put共同成交分钟开盘价，可以晚于信号，甚至跨日。若截至到期没有这样的分钟，保留到期结算，并明确显示“触发未成交”。这只是保守的数据配对要求；没有共同成交K线不意味着市场没有报价，也不保证延迟持有总是更保守。它可能使某个规则意外赚得更多。</p><p>8/7周期的退出触发没有后续共同成交分钟，回看最高与训练规则都未能模拟提前退出；8/14的训练止损信号等待65分钟才有共同分钟。真实组合限价单或逐腿交易可能给出不同结果，必须取得历史Bid/Ask或记录未来模拟成交才能校准。</p>{execution_table}<p class="muted">替代执行保持原信号不变，让两腿分别在信号后至少一分钟的首个成交分钟卖出，允许时间不同；每腿独立扣2%与$0.65。缺后续成交的腿保留至到期或最新估值。这是成交方式敏感性，不是更优策略的重新选参；逐腿操作还会短暂留下单边敞口。</p></section>
<section><h2>下一轮怎样观察这个候选</h2><ol><li>10:00先记录相同行权价、下周五到期的两腿可买价与股价，算费用占比；费用过高时考虑轮空。当前12%仅是待验证上限。</li><li>每10分钟以两腿可卖价计算净收益率，区分股价相对入场上涨还是下跌；候选为涨侧100%、跌侧2%。信号出现后卖出整组，不在本轮重新开仓。</li><li>同时记录信号价、实际可成交价、滑点、等待时间和没有成交的情况。净盈利2%的目标很薄，若两腿买卖差价就超过它，不能按成交末价当作已盈利。</li><li>继续保留“持有到期”对照；至少积累更多独立周期、覆盖涨跌及事件行情后，再重新评估参数。样本内赢家尚未通过后续验证，不应直接命名为实盘最优策略。</li></ol></section>
<section><h2>依据、数据与复现</h2><p>多头跨式的到期盈亏平衡点为行权价加减总权利金，时间价值损耗会影响持仓收益；参考 <a href="https://prd-web.optionseducation.org/strategies/all-strategies/long-straddle">OIC：Long Straddle</a>。成交末价与买卖报价不同，价差影响实际进出成本；参考 <a href="https://prd-web.optionseducation.org/news/understanding-the-bid-and-ask-prices-for-options">OIC：Bid and Ask Prices</a>。</p><p>计算输入为报告2实际成交聚合数据，未以理论模型补齐期权价格。程序：<a href="analyze_exit.py">分析程序</a>、<a href="build_report.py">报告生成器</a>；核验：损益对账、到期绝对值收益公式、信号无前视、成交晚于信号、入场过滤只用10:00前行情、未到期周期不用于选参。完整源码、数据指纹及规则评分随报告保存。</p></section>'''
css='''*{box-sizing:border-box}body{margin:0;background:#0e121b;color:#e7edf7;font:14px/1.8 system-ui,-apple-system,"PingFang SC",sans-serif;color-scheme:dark}main{max-width:1450px;margin:auto;padding:32px 24px}h1{font-size:31px;margin:8px 0}h2{font-size:21px;margin-top:0}.eyebrow{color:#f5ca75;letter-spacing:2px}.muted,small{color:#9cabbe}section{background:#171e2c;border:1px solid #2b3546;border-radius:14px;padding:24px;margin:22px 0}a{color:#79b7ff}.cards{display:grid;grid-template-columns:repeat(3,1fr);gap:16px}.card{background:#202a3b;padding:17px;border-radius:10px}.card strong{display:block;font-size:28px;color:#f5ca75}.note{border-left:3px solid #f5ca75;background:#f5ca7509;padding:14px}.scroll{overflow:auto;max-height:520px}table{border-collapse:collapse;width:100%;font-size:13px}th,td{border-bottom:1px solid #2b3546;padding:11px;text-align:right;white-space:nowrap}th{background:#202a3b;color:#9cabbe;position:sticky;top:0}td:first-child,th:first-child{text-align:left}td:nth-child(1){white-space:normal;min-width:115px}.toolbar,.legend{display:flex;gap:20px;flex-wrap:wrap;margin:14px 0}select{padding:9px;background:#202c3e;color:#e7edf7;border:1px solid #3b4960;border-radius:6px;font:inherit}.chartwrap{position:relative}canvas{width:100%;height:450px;display:block}#tip{position:absolute;display:none;pointer-events:none;background:#080e18f5;border:1px solid #738398;padding:12px;border-radius:9px;z-index:2;max-width:300px;font-size:12px}li{margin:8px 0}@media(max-width:750px){main{padding:15px}.cards{grid-template-columns:1fr}section{padding:16px}h1{font-size:24px}}'''
js=(P/'optimization_chart.js').read_text()
htmlout='<!doctype html><html lang="zh-CN"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>SKHY报告3：跨式退出与轮空优化</title><style>'+css+'</style><main>'+body+'</main><script>const D='+json.dumps(d,ensure_ascii=False,allow_nan=False).replace('</','<\\/')+';\n'+js+'</script></html>'
(P/'skhy_report3_exit_optimization.html').write_text(htmlout)
(P/'report3_summary.md').write_text(f'''# SKHY 报告3：退出与轮空优化

[打开完整交互报告](skhy_report3_exit_optimization.html)

六轮持有到期净收益：{money(total('baseline',range(6)))}。全样本回看最高：{money(total('full_sample_best',range(6)))}。

回看候选：{d['selected']['full_sample_best']['name']}。

训练规则：{d['selected']['train_selected']['name']}；后两轮验证{money(total('train_selected',[4,5]))}，同期持有到期{money(total('baseline',[4,5]))}。尚未验证出可靠最优策略。

7/31与8/14的较新报价毛盈利空间过薄，示例摩擦后最高仍亏损；费用上限只排除了一个昂贵样本，不能证明12%为普遍最优阈值。示例摩擦为每腿买入+2%、卖出−2%，每张每次佣金$0.65。交易按信号后的共同成交分钟估算，未保证真实成交。

仅六轮完整样本，8,217次规则比较存在严重过拟合风险。9/11未到期不用于选参。图表和逐轮信号/执行时间见完整报告。
''')
print('Built report 3')
