const $=id=>document.getElementById(id),fmt=n=>n==null?'—':Number(n).toLocaleString('en-US',{minimumFractionDigits:2,maximumFractionDigits:2});let C,R,key;
D.cycles.forEach((c,i)=>$('cycle').add(new Option(c.label+(c.completed?'':' · 未到期'),i)));
function xcoord(t){const slots={0:0,3:1,4:2,5:3,6:4,7:5},day=Math.round((Date.parse(t.slice(0,10))-Date.parse(C.start))/86400000);return slots[day]+(+t.slice(11,13)*60+(+t.slice(14,16))-570)/390*.92}
function net(p){if(p.pnl==null)return null;const v=C.capital+p.pnl,cost=C.capital*1.02+1.3;return p.kind==='expiry'?v-cost:v*.98-1.3-cost}
function optimized(p){return R.skipped?0:R.closed&&p.et>=R.exit?R.pnl:net(p)}
function render(){key=$('strategy').value;C=D.cycles[+$('cycle').value];R=D.selected_results[key][+$('cycle').value];$('ruleText').textContent=D.selected[key].name+(key==='full_sample_best'?'。这是事后全样本挑选结果，不能视为独立验证。':'');
$('roundTable').innerHTML='<div class="scroll"><table><thead><tr>'+['周期','买入成本含摩擦','信号时间 ET','模拟退出 ET','原因','所选净收益','到期/最新对照净收益','差额'].map(x=>'<th>'+x+'</th>').join('')+'</tr></thead><tbody>'+D.cycles.map((c,i)=>{const r=D.selected_results[key][i],b=D.selected_results.baseline[i];return '<tr>'+[c.label+(c.completed?'':'（未到期）'),'$'+fmt(r.cost),r.signal?.slice(5,16).replace('T',' ')||'—',r.skipped?'轮空':r.exit?.slice(5,16).replace('T',' ')||'—',r.reason+(r.unfilled_signal?'（触发未成交）':''),'$'+fmt(r.pnl),'$'+fmt(b.pnl),'$'+fmt(r.pnl-b.pnl)].map(x=>'<td>'+x+'</td>').join('')+'</tr>'}).join('')+'</tbody></table></div>';
$('roundInfo').textContent='本轮实际入场 '+C.entry_et.slice(0,16).replace('T',' ')+' ET；原始权利金 $'+fmt(C.capital)+'；策略 '+(R.skipped?'轮空':R.reason)+'。'+(R.delay!=null?'信号至共同成交分钟间隔 '+fmt(R.delay)+' 分钟。':'')+(R.unfilled_signal?'已触发退出但后续没有共同成交分钟，最终按到期或最新估值处理。':'');chart()}
function chart(){const canvas=$('chart'),ctx=canvas.getContext('2d'),w=canvas.clientWidth,h=450,ratio=window.devicePixelRatio||1;canvas.width=w*ratio;canvas.height=h*ratio;ctx.scale(ratio,ratio);$('tip').style.display='none';const l=76,r=72,t=32,b=46,pw=Math.max(1,w-l-r),ph=h-t-b,X=x=>l+x/6*pw;
const vals=C.points.flatMap(p=>[net(p),optimized(p)]).filter(v=>v!=null);let min=Math.min(0,...vals),max=Math.max(0,...vals);const pad=(max-min)*.1||1;min-=pad;max+=pad;const stocks=C.points.map(p=>p.stock_return_pct).filter(v=>v!=null);let slo=Math.min(0,...stocks),shi=Math.max(0,...stocks),spad=(shi-slo)*.1||1;slo-=spad;shi+=spad;const Y=v=>t+(max-v)/(max-min)*ph,S=v=>t+(shi-v)/(shi-slo)*ph;
function draw(active){ctx.clearRect(0,0,w,h);ctx.font='12px system-ui';ctx.textBaseline='middle';['本周五','周一','周二','周三','周四','下周五'].forEach((label,i)=>{ctx.fillStyle=i%2?'#202a3b':'#171e2c';ctx.fillRect(X(i),t,pw/6*.92,ph);ctx.fillStyle='#9cabbe';ctx.textAlign='center';ctx.fillText(label,X(i+.46),h-20)});
for(let i=0;i<=4;i++){const y=t+ph*(1-i/4);ctx.strokeStyle='#2b3546';ctx.lineWidth=1;ctx.beginPath();ctx.moveTo(l,y);ctx.lineTo(w-r,y);ctx.stroke();ctx.fillStyle='#ffd166';ctx.textAlign='right';ctx.fillText(fmt(min+(max-min)*i/4),l-7,y);ctx.textAlign='left';ctx.fillStyle='#38bdf8';ctx.fillText(fmt(slo+(shi-slo)*i/4)+'%',w-r+7,y)}
for(const [zero,color,label,side] of [[Y(0),'#ffd166','总收益 $0',0],[S(0),'#38bdf8','股票 0%',1]]){ctx.strokeStyle=ctx.fillStyle=color;ctx.setLineDash(side?[3,5]:[9,5]);ctx.beginPath();ctx.moveTo(l,zero);ctx.lineTo(w-r,zero);ctx.stroke();ctx.setLineDash([]);ctx.textAlign=side?'right':'left';ctx.fillText(label,side?w-r-4:l+4,zero-9)}
for(const [field,color,transform,axis] of [['baseline','#ffd166',net,Y],['optimized','#43caaa',optimized,Y],['stock','#38bdf8',p=>p.stock_return_pct,S]]){ctx.strokeStyle=color;ctx.lineWidth=field==='optimized'?3:2;ctx.beginPath();let last=null;for(const p of C.points){const v=transform(p);if(v==null){last=null;continue}const x=X(xcoord(p.et)),y=axis(v);if(!last||last.day!==p.day)ctx.moveTo(x,y);else ctx.lineTo(x,y);last=p}ctx.stroke()}
if(R.closed&&!R.skipped&&R.exit){const x=X(xcoord(R.exit));ctx.strokeStyle='#43caaa';ctx.lineWidth=1;ctx.setLineDash([2,4]);ctx.beginPath();ctx.moveTo(x,t);ctx.lineTo(x,h-b);ctx.stroke();ctx.setLineDash([]);ctx.fillStyle='#43caaa';ctx.beginPath();ctx.arc(x,Y(R.pnl),5,0,Math.PI*2);ctx.fill();ctx.textAlign=x>w/2?'right':'left';ctx.fillText('退出',x+(x>w/2?-8:8),t+12)}
if(active){const x=X(xcoord(active.et));ctx.strokeStyle='#9cabbe';ctx.setLineDash([3,4]);ctx.beginPath();ctx.moveTo(x,t);ctx.lineTo(x,h-b);ctx.stroke();ctx.setLineDash([])}
}
draw();canvas.onpointermove=e=>{const rect=canvas.getBoundingClientRect(),mouse=e.clientX-rect.left,x=(mouse-l)/pw*6,p=C.points.reduce((a,b)=>Math.abs(xcoord(b.et)-x)<Math.abs(xcoord(a.et)-x)?b:a,C.points[0]);draw(p);const tip=$('tip');tip.innerHTML='<b>'+p.et.slice(0,16).replace('T',' ')+' ET</b><br><span style="color:#ffd166">原持仓净估值 $'+fmt(net(p))+'</span><br><span style="color:#43caaa">所选规则净损益 $'+fmt(optimized(p))+'</span><br><span style="color:#38bdf8">股价 '+fmt(p.stock_return_pct)+'%</span><br>Call $'+fmt(p.call)+' / Put $'+fmt(p.put)+'<br>价格年龄 Call '+(p.call_age??'—')+' / Put '+(p.put_age??'—')+' 分钟<br>'+p.kind;tip.style.display='block';tip.style.left=Math.max(0,Math.min(w-tip.offsetWidth,mouse> w/2?mouse-tip.offsetWidth-15:mouse+15))+'px';tip.style.top=Math.max(0,Math.min(h-tip.offsetHeight,e.clientY-rect.top-tip.offsetHeight/2))+'px'};canvas.onpointerleave=()=>{draw();$('tip').style.display='none'};
}
$('strategy').onchange=render;$('cycle').onchange=render;window.addEventListener('resize',chart);render();
